#ifndef LIBDRIVERORACLE_GLOBAL_H
#define LIBDRIVERORACLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBDRIVERORACLE_LIBRARY)
#  define LIBDRIVERORACLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBDRIVERORACLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBDRIVERORACLE_GLOBAL_H
